import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./src/components/styles/main.css";
import BgEffectContainer from "./src/components/layouts/BgEffectContainer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <div className="absolute h-full w-full">
        <BgEffectContainer/>
        </div>
        {children}
      </body>
    </html>
  );
}
